<?php
$this->headTitle($this->title);
?>

<div class="container">
    <div class="row no-gutters">
        <div class="col-12">
            <h4 class="col-12"> Create Albums</h4>
            <span>
                <button type="button" id="add_button" data-toggle="modal" data-target="#albumModal" style="cursor:pointer; color:white;" class="btn btn-success col-3 mb-4">Add</button>
            </span>
            <table id="user_data" class="table table-striped table-bordered table-hover" style="width:100%;" id="albumTable">
                <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Title</th>
                        <th scope="col">Artists</th>
                        <th scope="col">Tags</th>

                        <th id="removeSort" scope="col">Action</th>
                    </tr>

                </thead>
            </table>
        </div>
    </div>
</div>


<div id="albumModal" tabindex="-1" class="modal fade" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Modal body text goes here.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>


<?php
// for css files use appendStylesheet
// $this->headLink()->appendStylesheet($this->baseUrl() . '/css/albums.css', 'screen');
?>

<?php
// for js files use appendFile
$this->headScript()->appendFile($this->baseUrl() . '/js/albums.js')
?>

<?php
// variables injected to CSS use $this->placeholder('styleData')->captureStart() and close it with $this->placeholder('styleData')->captureEnd()
$this->placeholder('styleData')->captureStart(); ?>
<!-- .bold-labels .radio-inline, .checkbox-inline{
font-weight:bold;
} -->
<?php $this->placeholder('styleData')->captureEnd() ?>

<?php
// variables injected to JS use $this->placeholder('jsData')->captureStart() and close it with $this->placeholder('jsData')->captureEnd()

$this->placeholder('jsData')->captureStart(); ?>
var albumsTableLink ='<?= $this->url(['module' => 'default', 'controller' => 'index', 'action' => 'albums']) ?>';

<?php $this->placeholder('jsData')->captureEnd() ?>