<?php
$this->headTitle($this->title);
?>

<p><a href="<?= $this->url(['controller' => 'index', 'action' => 'add']); ?>">Add new album</a></p>
<div class="container">
    <h4><a href="<?= $this->url(['controller' => 'index', 'action' => 'add']); ?>">Create Albums</a></h4>
    <table class="table table-striped table-bordered table-hover" id="albumTable">
        <thead>
            <th scope="col">ID</th>
            <th scope="col">Artists</th>
            <th scope="col">Title</th>
            <th id="removeSort" scope="col">Action</th>
        </thead>
    </table>

</div>

<?php
// for css files use appendStylesheet
// $this->headLink()->appendStylesheet($this->baseUrl() . '/css/albums.css', 'screen');
?>

<?php
// for js files use appendFile
$this->headScript()->appendFile($this->baseUrl() . '/js/albums.js')
?>

<?php
// variables injected to CSS use $this->placeholder('styleData')->captureStart() and close it with $this->placeholder('styleData')->captureEnd()
$this->placeholder('styleData')->captureStart(); ?>
<!-- .bold-labels .radio-inline, .checkbox-inline{
font-weight:bold;
} -->
<?php $this->placeholder('styleData')->captureEnd() ?>


<?php
// variables injected to JS use $this->placeholder('jsData')->captureStart() and close it with $this->placeholder('jsData')->captureEnd()
$this->placeholder('jsData')->captureStart(); ?>
var username = '<?= $this->username; ?>';
var albumsTableLink ='<?= $this->url(array('module' => 'default', 'controller' => 'index', 'action' => 'albums', null, true)) ?>';
<?php $this->placeholder('jsData')->captureEnd() ?>