<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Zend Framework Tutorial');
echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
    <?= $this->headMeta(); ?>
    <?= $this->headTitle(); ?>
    <?= $this->headLink()->prependStylesheet($this->baseUrl() . '/css/site.css'); ?>
</head>

<body>
    <div id="content">
        <h1><?= $this->escape($this->title); ?></h1>
        <?= $this->layout()->content; ?>
    </div>
</body>

</html>